<?php
/**
 * Copyright (C) $user$, Inc - All Rights Reserved
 *
 *  <other text>
 * @file        QueueManager.php
 * @author      ignatenkovnikita
 * @date        $date$
 */

namespace common\modules\queuemanager;

use Yii;
use yii\base\Application;
use yii\base\BootstrapInterface;
use yii\base\Event;
use yii\base\Module;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\queue\Queue;

class QueueManager extends Module implements BootstrapInterface
{
    public $adminPermission = 'queuemanager-module';

    public $controllerNamespace = 'common\modules\queuemanager\controllers';

    public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                'access' => [
                    'class' => AccessControl::className(),
                    'rules' => [
                        [
                            'allow' => true,
                            'roles' => [$this->adminPermission]
                        ]
                    ]
                ]
            ]
        );
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->registerTranslations();
    }

    public function registerTranslations()
    {
        Yii::$app->i18n->translations['queuemanager'] = [
            'class' => 'yii\i18n\PhpMessageSource',
            'sourceLanguage' => 'en-US',
            'basePath' => '@backend/modules/queuemanager/messages',
        ];

    }


    public static function getMenuItems(){


        return

            [
                'label' => Yii::t('backend', 'Others'),
                'url' => '#',
                'icon' => '<i class="fa fa-code"></i>',
                'options' => ['class' => 'treeview'],
                'active' => (Yii::$app->controller->module->id == 'queuemanager') || (Yii::$app->controller->module->id == 'integration') ,
                'visible' => Yii::$app->user->can('queuemanager-module') || Yii::$app->user->can('integration-module'),
                'items' => [
                    [
                        'label' => Yii::t('integration', 'My integrations'),
                        'url' => ['/integration/integration-byuser/index'],
                        'icon' => '<i class="fa fa-folder-open-o"></i>',
                        'active' => (Yii::$app->controller->id == 'default') &&(Yii::$app->controller->module->id == 'integration'),
                    ],
                    [
                        'label' => Yii::t('integration', 'Integrations'),
                        'url' => ['/integration/integration-list/index'],
                        'icon' => '<i class="fa fa-folder-open-o"></i>',
                        'active' => (Yii::$app->controller->id == 'integration-list') &&(Yii::$app->controller->module->id == 'integration'),
                    ],
                    [
                        'label' => Yii::t('backend', 'Queue Manager'),
                        'url' => ['/queuemanager/default/index'],
                        'icon' => '<i class="fa fa-folder-open-o"></i>',
                        'active' => (Yii::$app->controller->id == 'default') && (Yii::$app->controller->module->id == 'queuemanager'),
                    ],

                ],
            ];

    }


    public function bootstrap($app)
    {
        if ($app instanceof \yii\console\Controller) {
            $this->controllerNamespace = '@common\modules\queuemanager\commands\controllers';
        }
    }


}